version: '3.8'

services:
  n8n:
    container_name: n8n
    restart: unless-stopped
    image: n8nio/n8n:1.90.0
    networks: ['ai_network']
    ports:
        - 5678:5678
    environment:
      - N8N_PORT=5678
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENCRYPTION_KEY
      - N8N_USER_MANAGEMENT_JWT_SECRET
      - GENERIC_TIMEZONE
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./shared:/data/shared
    env_file:
      - .env

  qdrant:
    image: qdrant/qdrant:v1.14.1
    hostname: qdrant
    container_name: qdrant
    networks: ['ai_network']
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  n8n_storage:
  qdrant_storage:

networks:
  ai_network: